spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.16.30.46:3306/fep?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Hxjr2018.
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 1000



  freemarker:
    check-template-location: false
    profiles:
      active: dev
    jackson:
      time-zone: GMT+8
    data:
      redis:
        repositories:
          enabled: false

    #\u914D\u7F6E Jpa
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: true

    redis:
      #\u6570\u636E\u5E93\u7D22\u5F15
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      #\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
      timeout: 5000





task:
  pool:
    # \u6838\u5FC3\u7EBF\u7A0B\u6C60\u5927\u5C0F
    core-pool-size: 10
    # \u6700\u5927\u7EBF\u7A0B\u6570
    max-pool-size: 30
    # \u6D3B\u8DC3\u65F6\u95F4
    keep-alive-seconds: 60
    # \u961F\u5217\u5BB9\u91CF
    queue-capacity: 50


server:
  port: 8080
  servlet:
    context-path: /myyh

#\u5BC6\u7801\u52A0\u5BC6\u4F20\u8F93\uFF0C\u524D\u7AEF\u516C\u94A5\u52A0\u5BC6\uFF0C\u540E\u7AEF\u79C1\u94A5\u89E3\u5BC6
rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEA0vfvyTdGJkdbHkB8mp0f3FE0GYP3AYPaJF7jUd1M0XxFSE2ceK3k2kw20YvQ09NJKk+OMjWQl9WitG9pB6tSCQIDAQABAkA2SimBrWC2/wvauBuYqjCFwLvYiRYqZKThUS3MZlebXJiLB+Ue/gUifAAKIg1avttUZsHBHrop4qfJCwAI0+YRAiEA+W3NK/RaXtnRqmoUUkb59zsZUBLpvZgQPfj1MhyHDz0CIQDYhsAhPJ3mgS64NbUZmGWuuNKp5coY2GIj/zYDMJp6vQIgUueLFXv/eZ1ekgz2Oi67MNCk5jeTF2BurZqNLR3MSmUCIFT3Q6uHMtsB9Eha4u7hS31tj1UWE+D+ADzp59MGnoftAiBeHT7gDMuqeJHPL4b+kC+gzV4FGTfhR9q3tTbklZkD2A==

jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key
#\u767B\u5F55\u56FE\u5F62\u9A8C\u8BC1\u7801\u6709\u6548\u65F6\u95F4/\u5206\u949F
loginCode:
  expiration: 2



  # 文件存储路径
file:
  path: C:\eladmin\file\
  avatar: C:\eladmin\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5