spring:
  profiles:
    active: dev
  #redis配置,默认情况下redis会创建16个数据库，Redis客户端的目标数据库为0号数据库，但客户端可以通过执行SELECT命令来切换目标数据库。
  redis:
    host: 39.105.174.141
    password:
    port: 6379
    timeout: 6000
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://39.105.174.141:3306/ry?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
#    url: jdbc:mysql://39.105.174.141:3306/ry?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: QQkaitaiji5

    #hikari数据库连接池
    hikari:
      pool-name: RY_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1
  cache:
    #ehcache配置文件路径
    ehcache:
      config: classpath:/ehcache/ehcache.xml
    #指定缓存类型，可加可不加
    type: redis
  jpa:
    show-sql: false  #在日志里显示执行的sql语句
    database: mysql
    hibernate:
      ddl-auto: update #每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect    #使用InnoDB引擎
  aop:
    auto: true
    proxy-target-class: true
server:
  port: 8888
  servlet:
    context-path: /

#登录验证码有效时间/分钟
loginCode:
  expiration: 5

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token
  # 验证码
  code-key: code-key


#密码加密传输，前端公钥加密，后端私钥解密
rsa:
  private_key: MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEA3zoHVXjt5RGQ9v1IRjyIEio0SVE7DjY2+rQMFM3YUBLUZ4ySWYKc1DoOlGOvOR80yuZvm8KtTAOIzvVbZGETJQIDAQABAkEA1NkmCQ/n9pYLXhcghShOrtNjS82Su/hh8CchpeypJ58kdUT12UrZGrsLStzqhu6InwrrQwvi+Rg0pYJ4bIOhuQIhAPk+wVbF0WzaUy0fJYqjemQAP99NOqoO0CgCBeFMLka/AiEA5UbCWtM+qvnT2PhX0sAY4kUJN9Xlf41Z3PiomMyMoxsCIQC6FTlBcIVPsJyCxos/u5eny2vkaoNO7apJBGGheD/gfwIhANlx2WQgUp//Hl75cPlsvGzkQpDU6LqnCWIb5nI8FOmfAiBuiO2jOMnuq2dqwKmyPoBTQhNdzN23QDiljyew3HNbGg==
# 文件存储路径
file:
  path: /data/file/
  avatar: /data/avatar/
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5


#logback配置
logging:
  file:
    #每个日志文件的大小
    #轮转保存3天
    name: ry_admin.log
    max-size: 5MB
    max-history: 3
    #和name一起配置只会生效一个，这里使用name
    path: /data/log
  pattern:
#    level: 用户:%X{user:-未登录} %5p
    level: :%X{user:-_MYYH} %10p

    #日志级别设置，所有service打印debug级别日志
  level:
    root: info
    ry: info
    tomcat: info
    org.hibernate: info
    #分组打印，tomcat，和system下的所有日志
    com.baomidou.example.mapper: info
  group:
    tomcat: org.apache.catalina, org.apache.coyote, org.apache.tomcat
    ry: com.myyh.system
